### ISSUE TITLE
[Week1] 스택&큐

### ISSUE THREAD

**Issue by yeeuniii** [yeeuniii/study-algorithm#1]
## ToDo
- [x] 스택 & 큐 개념 정리 및 구현
- 문제풀이
  - [x] 백준 10828번. 스택
  - [x] 백준 1158번. 요세푸스 문제
  - [x] 프로그래머스. 다리를 지나는 트럭
  - [x] 백준 9012번. 괄호
  - [x] 백준 1966. 프린터 큐
  - [x] 백준 9093번. 단어 뒤집기
  - 옵션
  - [ ] 프로그래머스. 주식가격
  - [ ] 프로그래머스. 프린터
 - [x] 일요일 팀미션 준비
 ### 책
 - Chapter1
   - [x] 빅오 표기법
- Chapter2
   - [ ] 배열 & 연결 리스트 개념 정리 및 구현
   - [ ] 선택 정렬 구현
- Chapter3 
  - [ ] 재귀 개념 익히기
- Chapter4 
  - [ ] 퀵 정렬 개념 정리 및 구현

**Comment by yeeuniii** [comment]
다리를 지나는 트럭 오답노트:
https://glory-banana-f15.notion.site/1-Day3-ef45102920eb4f409fe57bf3ba0e3fdd?pvs=4

**Comment by yeeuniii** [comment]
요세푸스 문제 오답노트:
https://glory-banana-f15.notion.site/1-Day2-aa7140f209f94700b0e7ae1bfec4118e?pvs=4

**Comment by yeeuniii** [comment]
스택 오답노트:
https://glory-banana-f15.notion.site/1-Day1-44e16dbe82964658ab72b5c23acc87a8?pvs=4

**Comment by yeeuniii** [comment]
프린터 큐 오답노트:
https://glory-banana-f15.notion.site/1-Day5-fed5dfe20bbd4ba799c53ae2d7314afb?pvs=4

**Comment by yeeuniii** [comment]
괄호 오답노트:
https://glory-banana-f15.notion.site/1-Day4-be36ce8aa0914a8fa040632fbf265778?pvs=4

**Comment by yeeuniii** [comment]
단어 뒤집기 오답노트: 
https://glory-banana-f15.notion.site/1-Day6-bcb2fa36364542d9bf64adb0a436ba54?pvs=4
