### ISSUE TITLE
[Week2] DFS/BFS

### ISSUE THREAD

**Issue by yeeuniii** [yeeuniii/study-algorithm#3]
# ToDo
- [x] 노하우 영상 보기
- [x] 시간복잡도 개념 정리
  - [ ] 공간복잡도도
- [x] DFS/BFS 개념 정리 및 구현
- [x] 일요일 팀발표 준비
---
## 문제 풀이
  - [x] 백준 1260 DFS와 BFS
  - [x] 백준 2667 단지번호 붙이기
  - [x] 백준 11724 연결 요소의 개수
  - [x] 백준 1012 유기농 배추
  - [x] 백준 1697 숨바꼭질
  - [x] 백준  2178 미로탐색
  - 스택/큐
  - [ ] 프로그래머스. 주식 가격
  - [ ] 프로그래머스. 프린터
  - 옵션
 --- 
## 책
- Chapter2
   - [ ] 배열 & 연결 리스트 개념 정리 및 구현
   - [ ] 선택 정렬 구현
 - Chapter6
   - [x] 너비 우선 탐색
---
## ToDo Later
- [ ] 단지번호 붙이기 - BFS
- [ ] 숨바꼭질 - DP
- [ ] 2167 배열의 합 - 누적합

**Comment by yeeuniii** [comment]
시간복잡도 개념정리:
https://glory-banana-f15.notion.site/1987baf703064eb3bb96add04994ef62?pvs=4

**Comment by yeeuniii** [comment]
BFS/DFS 개념정리:
https://glory-banana-f15.notion.site/BFS-DFS-754644704a4842ebafb07940b612e33d?pvs=4

**Comment by yeeuniii** [comment]
DFS와 BFS 오답노트:
https://glory-banana-f15.notion.site/2-Day1-4e42801e9c814facaa0f8f2f6fadb4ec?pvs=4

**Comment by yeeuniii** [comment]
단지번호 붙이기 오답노트:
https://glory-banana-f15.notion.site/2-Day2-9fd689551d1a4e909b3502deb0f8b04b?pvs=4

**Comment by yeeuniii** [comment]
연결 요소의 개수 오답노트:
https://glory-banana-f15.notion.site/2-Day3-bfba46211d9f4a9ea569ca952b86a78a?pvs=4

**Comment by yeeuniii** [comment]
유기농 배추 오답노트:
https://glory-banana-f15.notion.site/2-Day4-bb415a795f6b4c8aa8abf82d4023e68c?pvs=4

**Comment by yeeuniii** [comment]
숨바꼭질 오답노트:
https://glory-banana-f15.notion.site/2-Day5-acb7d3d321954f82b98ee9a8154de492?pvs=4

**Comment by yeeuniii** [comment]
미로 탐색 오답노트:
https://glory-banana-f15.notion.site/2-Day6-0d027d108cde46bd87db24d406e6ac35?pvs=4
