### ISSUE TITLE
[Week3] 백트래킹

### ISSUE THREAD

**Issue by yeeuniii** [yeeuniii/study-algorithm#5]
# ToDo
- [x] 노하우 영상 보기
- [x] 백트래킹 개념 정리 및 구현
  - [x] n-queen 문제 풀이
- [x] 일요일 팀발표 준비
---
## 문제 풀이
  - [x] 백준 15663 N과 M (9)
  - [x] 백준 15651 N과 M (3)
  - [x] 백준 6987 월드컵
  - [x] 백준 1182 부분 수열의 합
  - [x] 백준 1759 암호 만들기
  - [x] 백준 2661 좋은 수열
  - 스택/큐
  - [ ] 프로그래머스. 주식 가격
  - [ ] 프로그래머스. 프린터
  - DFS/BFS
  - [x] 숨바꼭질2
 --- 
## 책
- Chapter2
   - [ ] 배열 & 연결 리스트 개념 정리 및 구현
   - [ ] 선택 정렬 구현
---
