### ISSUE TITLE
[Week4] 이진탐색/DP

### ISSUE THREAD

**Issue by yeeuniii** [yeeuniii/study-algorithm#6]
# ToDo
- [ ] 노하우 영상 보기
- [x] 이진탐색 개념 정리 및 구현
- [x] DP 개념 정리 및 구현
  - [x] 피보나치 
  - [x] 배낭 문제
- [x] 일요일 팀발표 준비
- [x] 분할정복 알고리즘 공부
---
## 문제 풀이
  - [x] 프로그래머스. 입국심사
  - [x] 백준 2805 나무 자르기
  - [x] 백준 1654 랜선 자르기
  - [x] 백준 12026 BOJ 거리
  - [x] 백준 1495 기타리스트
  - [x] 백준 1890 점프
  - 스택/큐
  - [ ] 프로그래머스. 주식 가격
  --- 
## 책
- Chapter2
  - [x] 배열 & 연결 리스트 개념 정리 및 구현
  - [x] 선택 정렬 구현
- Chapter3
   - [x] 재귀
- Chapter4
   - [x] 퀵 정렬
- Chapter8
   - [ ] 탐욕 알고리즘
- Chapter9
   - [x] 동적 프로그래밍
---
## ToDo Later

- [ ] 배낭 문제 시간 줄이는 코드 구성해보기
