### ISSUE TITLE
[August]

### ISSUE THREAD

**Issue by yeeuniii** [yeeuniii/study-algorithm#9]
# Plan
- [ ] 둘째주 : 스택 / 큐 + 그리디
- [ ] 셋째주 : DFS / BFS + 해시
- [ ] 넷째주 : 백트래킹 + 정렬
- [ ] 다섯째주 : 이진탐색 / DP + 

> ## 한 주 동안 할 일
- 밀라 알고리즘 스터디에서 어려웠던 문제 다시 한 번 풀기
- 옵션 문제  풀기
- 알고리즘 개념 하나 추가 공부
  - 해시, 그리디, 정렬 

## ToDo
- [ ] 노하우 총정리
- [ ] 벨로그에 개념 정리
- [ ] 책 다 읽기
